/**
 * Export utilities for different file formats
 */

/**
 * Export content as plain text file
 */
export function exportAsTxt(
  content: string,
  filename: string = "result",
): void {
  const blob = new Blob([content], { type: "text/plain" });
  downloadBlob(blob, `${filename}.txt`);
}

/**
 * Export content as Markdown file
 */
export function exportAsMarkdown(
  content: string,
  filename: string = "result",
): void {
  const blob = new Blob([content], { type: "text/markdown" });
  downloadBlob(blob, `${filename}.md`);
}

/**
 * Export content as PDF (client-side text-to-PDF)
 * Note: This is a simple implementation. For better PDF quality, consider using a library like jsPDF
 */
export async function exportAsPDF(
  content: string,
  title: string = "AI Study Tools Result",
  filename: string = "result",
): Promise<void> {
  try {
    // Create a simple HTML structure for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>${title}</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              font-size: 12pt;
              line-height: 1.6;
              max-width: 8.5in;
              margin: 0.5in auto;
              padding: 20px;
            }
            h1 {
              color: #3b82f6;
              border-bottom: 2px solid #3b82f6;
              padding-bottom: 10px;
            }
            pre {
              white-space: pre-wrap;
              word-wrap: break-word;
              background: #f5f5f5;
              padding: 15px;
              border-radius: 5px;
            }
            .footer {
              margin-top: 40px;
              padding-top: 10px;
              border-top: 1px solid #ccc;
              color: #666;
              font-size: 10pt;
              text-align: center;
            }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <pre>${content}</pre>
          <div class="footer">
            Generated by ToolNova - toolnovahub.com<br>
            ${new Date().toLocaleString()}
          </div>
        </body>
      </html>
    `;

    // Use browser's print to PDF functionality
    const blob = new Blob([htmlContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);

    const printWindow = window.open(url, "_blank");
    if (printWindow) {
      printWindow.onload = () => {
        printWindow.print();
        setTimeout(() => {
          printWindow.close();
          URL.revokeObjectURL(url);
        }, 250);
      };
    }
  } catch (error) {
    console.error("PDF export failed:", error);
    throw new Error(
      "Failed to export as PDF. Please try downloading as TXT instead.",
    );
  }
}

/**
 * Export content as DOCX (using simple XML-based approach)
 * Note: This creates a basic Word-compatible document
 */
export function exportAsDocx(
  content: string,
  title: string = "AI Study Tools Result",
  filename: string = "result",
): void {
  // Simple DOCX structure (actually an XML that Word can open)
  const docxContent = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<w:wordDocument xmlns:w="http://schemas.microsoft.com/office/word/2003/wordml">
  <w:body>
    <w:p>
      <w:pPr>
        <w:jc w:val="left"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="32"/>
          <w:color w:val="3B82F6"/>
        </w:rPr>
        <w:t>${escapeXml(title)}</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r>
        <w:t></w:t>
      </w:r>
    </w:p>
    ${content
      .split("\n")
      .map(
        (line) => `
    <w:p>
      <w:r>
        <w:t>${escapeXml(line)}</w:t>
      </w:r>
    </w:p>
    `,
      )
      .join("")}
    <w:p>
      <w:r>
        <w:t></w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:jc w:val="center"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:sz w:val="16"/>
          <w:color w:val="666666"/>
        </w:rPr>
        <w:t>Generated by ToolNova - toolnovahub.com</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:jc w:val="center"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:sz w:val="16"/>
          <w:color w:val="666666"/>
        </w:rPr>
        <w:t>${new Date().toLocaleString()}</w:t>
      </w:r>
    </w:p>
  </w:body>
</w:wordDocument>`;

  const blob = new Blob([docxContent], {
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  });
  downloadBlob(blob, `${filename}.docx`);
}

/**
 * Copy content as HTML to clipboard
 */
export async function copyAsHTML(content: string): Promise<void> {
  const htmlContent = `<pre style="font-family: monospace; white-space: pre-wrap;">${escapeHtml(content)}</pre>`;

  try {
    await navigator.clipboard.write([
      new ClipboardItem({
        "text/html": new Blob([htmlContent], { type: "text/html" }),
        "text/plain": new Blob([content], { type: "text/plain" }),
      }),
    ]);
  } catch (error) {
    // Fallback to plain text
    await navigator.clipboard.writeText(content);
  }
}

/**
 * Utility: Download a Blob as a file
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Utility: Escape XML special characters
 */
function escapeXml(unsafe: string): string {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * Utility: Escape HTML special characters
 */
function escapeHtml(unsafe: string): string {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * Format file size for display
 */
export function formatFileSize(bytes: number): string {
  if (bytes === 0) return "0 Bytes";
  const k = 1024;
  const sizes = ["Bytes", "KB", "MB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + " " + sizes[i];
}
