"use strict";
"use client";

import EnhancedToolLayout from "@/components/EnhancedToolLayout";
export default function PlagiarismCheckerClient() {
  const promptTemplate = (input: string) => {
    return `You are an advanced AI detection algorithm and plagiarism expert. Your job is to analyze text for robotic patterns, repetitive structures, common AI buzzwords, and lack of human variance (perplexity/burstiness). Provide a harsh but accurate assessment of how likely the text is generated by AI, and give constructive feedback to humanize it.
    
Analyze the following text for signs of AI generation and potential plagiarism.
    
Text to analyze:
"${input}"

Please provide your analysis in the following Markdown format:
## AI Detection Analysis
[Provide an estimated percentage of how much of this text appears to be AI-generated, e.g., "Probability of AI generation: 85%"]

## Detailed Breakdown
[Identify specific robotic patterns, repetitive structures, or lack of "burstiness" and "perplexity" (common AI footprints)]

## Originality Assessment
[Mention if the concepts sound generic or highly derivative]

## Humanization Suggestions
[Provide 3-4 actionable tips on how the author can rewrite this text to make it sound more natural, human, and authentic]`;
  };

  return (
    <EnhancedToolLayout
      toolSlug="plagiarism-checker"
      toolName="AI Plagiarism Checker"
      placeholder="Paste your essay or article here to analyze..."
      promptTemplate={promptTemplate as any}
      options={[]}
    />
  );
}
