
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Disclaimer | ToolNova",
    description: "Legal disclaimer for using ToolNova's AI-powered tools. Understand the limitations and responsibilities when using our platform.",
    alternates: {
        canonical: "https://www.toolnovahub.com/disclaimer",
    },
};

export default function DisclaimerPage() {
    return (
        <div className="container mx-auto px-6 py-24 max-w-4xl text-slate-800 dark:text-slate-200">
            <h1 className="text-4xl font-bold mb-8">Disclaimer</h1>
            <p className="text-sm text-muted-foreground mb-12 italic">
                Last Updated: {new Date().toLocaleDateString()}
            </p>

            <div className="prose dark:prose-invert max-w-none space-y-10 leading-relaxed">
                <section>
                    <h2 className="text-2xl font-bold">1. General Information</h2>
                    <p>
                        The information provided by ToolNova ("we," "us," or "our") on
                        https://www.toolnovahub.com (the "Site") and our mobile applications
                        is for general informational purposes only. All information on the
                        Site is provided in good faith, however, we make no representation
                        or warranty of any kind, express or implied, regarding the accuracy,
                        adequacy, validity, reliability, availability, or completeness of
                        any information on the Site.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold">2. AI-Generated Content</h2>
                    <p>
                        ToolNova utilizes advanced Artificial Intelligence (AI) to generate
                        text, summaries, and transformations. While our models are
                        state-of-the-art, AI-generated content can occasionally be
                        inaccurate, biased, or incomplete.
                    </p>
                    <p className="mt-4 font-semibold text-primary">
                        Users are solely responsible for fact-checking and verifying
                        any output generated by our tools before using them in
                        professional, academic, or legal contexts.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold">3. No Professional Advice</h2>
                    <p>
                        The Site cannot and does not contain legal, financial, or
                        medical advice. The information is provided for general
                        informational and educational purposes only and is not a
                        substitute for professional advice. Accordingly, before
                        taking any actions based upon such information, we encourage
                        you to consult with the appropriate professionals.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold">4. External Links Disclaimer</h2>
                    <p>
                        The Site may contain (or you may be sent through the Site)
                        links to other websites or content belonging to or
                        originating from third parties. Such external links are
                        not investigated, monitored, or checked for accuracy,
                        adequacy, validity, reliability, availability, or
                        completeness by us.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold">5. Limitation of Liability</h2>
                    <p>
                        In no event shall ToolNova be liable for any special, direct,
                        indirect, consequential, or incidental damages or any damages
                        whatsoever, whether in an action of contract, negligence, or
                        other tort, arising out of or in connection with the use of
                        the Service or the contents of the Service.
                    </p>
                </section>

                <section className="bg-slate-50 dark:bg-slate-900 p-8 rounded-2xl border border-slate-100 dark:border-slate-800">
                    <h2 className="text-xl font-bold mb-4">Contact Us</h2>
                    <p>
                        If you have any questions regarding this disclaimer, please
                        reach out to us at:
                    </p>
                    <p className="mt-2 font-bold text-primary">
                        support@toolnovahub.com
                    </p>
                </section>
            </div>
        </div>
    );
}
